{{/*
This template serves as the blueprint for the cronjob objects that are created
within the common library.
*/}}
        {{- define "common.cronjob" }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: {{ include "app.fullname" . }}
    labels:
        {{- include "app.labels" . | nindent 4 }}
spec:
    {{- if .Values.cronjob }}
    schedule: {{ .Values.cronjob.schedule }}
    concurrencyPolicy:  {{ .Values.cronjob.concurrencyPolicy }}
    suspend: false
    jobTemplate:
        metadata:
            creationTimestamp: null
            labels:
            {{- include "app.labels" . | nindent 12 }}
        spec:
            backoffLimit: {{ .Values.cronjob.backoffLimit }}
            parallelism: {{ .Values.cronjob.parallelism }}
            template:
                spec:
                    containers:
                        - env:
                                {{- include "app.env" . | indent 8 }}
                          name: {{ include "app.name" . }}
                          image: {{ .Values.image.repository }}/{{ .Values.image.namespace }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
                                {{- include "app.resources" . | indent 26 }}
                          terminationMessagePath: /dev/termination-log
                          terminationMessagePolicy: File
                          imagePullPolicy: Always
                    restartPolicy: {{ .Values.cronjob.restartPolicy }}
                    terminationGracePeriodSeconds: 30
                    dnsPolicy: ClusterFirst
                    securityContext: {}
                    schedulerName: default-scheduler

        {{- end }}
    {{- end }}