{{/*
This template serves as the blueprint for the Deployment objects that are created
within the common library.
*/}}
{{- define "common.job" }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  backoffLimit: 0
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "app.labels" . | nindent 12 }}
    spec:
      containers:
        - env:
          {{- include "app.env" . | indent 8 }}
          name: {{ include "app.name" . }}
          image: {{ .Values.image.repository }}/{{ .Values.image.namespace }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          {{- include "app.resources" . | indent 10 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
{{- end }}