{{- define "common.pdb" }}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minavailable }}
  selector:
    matchLabels:
      app: {{ include "app.fullname" . }}
{{- end }}