{{/*
This template serves as the blueprint for the Deployment objects that are created
within the common library.
*/}}
{{- define "common.service" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
spec:
  ports:
    {{- if (.Values.service).ports }}
    {{- range .Values.service.ports }}
    - port: {{.}}
      protocol: TCP
      targetPort: {{.}}
      name: tcp-{{.}}
    {{- end}}
    {{- else}}
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: tcp-8080
    {{- end}}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
{{- end }}