{{/*
This template serves as the blueprint for the statefulset objects that are created
within the common library.
*/}}
        {{- define "common.statefulset" }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: {{ include "app.fullname" . }}
    labels:
        {{- include "app.labels" . | nindent 8 }}
spec:
    {{ if .Values.statefulset }}
    serviceName: {{ .Values.statefulset.serviceName }}
    replicas:  {{ .Values.statefulset.replicas }}
    selector:
        matchLabels:
        {{- include "app.labels" . | nindent 12 }}
    template:
        metadata:
            labels:
            {{- include "app.labels" . | nindent 16 }}
        spec:
            terminationGracePeriodSeconds: 10
            containers:
                - name: {{ include "app.fullname" . }}
                  image: {{ .Values.image.repository }}/{{ .Values.image.namespace }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
                  {{- include "app.resources" . | indent 18 }}
        {{- end }}

        {{- end -}}